// <auto-generated />
using GeoAPI.Geometries;
using MapperTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

namespace MapperTest.Data.Migrations
{
    [DbContext(typeof(MapperContext))]
    [Migration("20190612202409_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MapperTest.Domain.Fixture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<IPoint>("Coords")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<long>("FixtureTypeID");

                    b.Property<long>("MapId");

                    b.HasKey("Id");

                    b.HasIndex("FixtureTypeID");

                    b.HasIndex("MapId");

                    b.ToTable("Fixtures");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-316 2285)"),
                            FixtureTypeID = 1L,
                            MapId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-299 707.5)"),
                            FixtureTypeID = 1L,
                            MapId = 1L
                        });
                });

            modelBuilder.Entity("MapperTest.Domain.FixtureType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("FixtureTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Fire Extinguisher"
                        });
                });

            modelBuilder.Entity("MapperTest.Domain.Map", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Building")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Floor")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Maps");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Building = "Courthouse",
                            Description = "IT Deptartment",
                            Floor = "2"
                        });
                });

            modelBuilder.Entity("MapperTest.Domain.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Point>("Coords")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("MapId");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-659 315.5)"),
                            FirstName = "Amy",
                            LastName = "Kaup",
                            MapId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-704 515.5)"),
                            FirstName = "Dan",
                            LastName = "Brandl",
                            MapId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-642 771)"),
                            FirstName = "Wendy",
                            LastName = "Markworth",
                            MapId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-718 1089)"),
                            FirstName = "Chris",
                            LastName = "Markworth",
                            MapId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-702 1283)"),
                            FirstName = "Matt",
                            LastName = "Ives",
                            MapId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-704 1597)"),
                            FirstName = "Lisa",
                            LastName = "Keller",
                            MapId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-702 1803)"),
                            FirstName = "Jason",
                            LastName = "DeMarco",
                            MapId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-706 2103)"),
                            FirstName = "Dave",
                            LastName = "Schreiber",
                            MapId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-716 2307)"),
                            FirstName = "Phil",
                            LastName = "Anderson",
                            MapId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-240 1249)"),
                            FirstName = "Carolynn",
                            LastName = "Martin",
                            MapId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-122 1253)"),
                            FirstName = "Jason",
                            LastName = "McDonald",
                            MapId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-240 1661)"),
                            FirstName = "Steven",
                            LastName = "Xiong",
                            MapId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            Coords = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=0;POINT (-116 1665)"),
                            FirstName = "Matt",
                            LastName = "Thomas",
                            MapId = 1L
                        });
                });

            modelBuilder.Entity("MapperTest.Domain.Fixture", b =>
                {
                    b.HasOne("MapperTest.Domain.FixtureType", "FixtureType")
                        .WithMany("Fixtures")
                        .HasForeignKey("FixtureTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MapperTest.Domain.Map", "Map")
                        .WithMany("Fixtures")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapperTest.Domain.Person", b =>
                {
                    b.HasOne("MapperTest.Domain.Map", "Map")
                        .WithMany("Persons")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
